version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - mvn install
  build:
    commands:
      - echo Building the project...
      - mvn package
  post_build:
    commands:
      - echo Build completed successfully.
artifacts:
  files:
    - target/addressbook-cicd-project*.jar
  discard-paths: yes
