version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - mvn install
  build:
    commands:
      - echo Building the project...
      - mvn package
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
